ALTER TABLE "users" DROP CONSTRAINT "users_user_auth0_id_fkey";
ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_user_id_fkey";
ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_role_id_fkey";
ALTER TABLE "user_wallets" DROP CONSTRAINT "user_wallets_user_id_fkey";
ALTER TABLE "user_wallets" DROP CONSTRAINT "user_wallets_wallet_source_id_fkey";
ALTER TABLE "user_wallets" DROP CONSTRAINT "user_wallets_wallet_currency_id_fkey";
ALTER TABLE "user_budgets" DROP CONSTRAINT "user_budgets_user_id_fkey";
ALTER TABLE "user_budgets" DROP CONSTRAINT "user_budgets_transaction_period_id_fkey";
ALTER TABLE "user_goals" DROP CONSTRAINT "user_goals_user_id_fkey";
ALTER TABLE "user_goals" DROP CONSTRAINT "user_goals_transaction_period_id_fkey";
ALTER TABLE "goal_transactions" DROP CONSTRAINT "goal_transactions_user_id_fkey";
ALTER TABLE "goal_transactions" DROP CONSTRAINT "goal_transactions_goal_id_fkey";
ALTER TABLE "user_tranfers" DROP CONSTRAINT "user_transfers_user_id_fkey";
ALTER TABLE "user_transfers" DROP CONSTRAINT "user_transfers_user_id_receiver_fkey";
ALTER TABLE "user_transfers" DROP CONSTRAINT "user_transfers_user_id_sender_fkey";
ALTER TABLE "user_incomes" DROP CONSTRAINT "user_incomes_user_id_fkey";
ALTER TABLE "user_incomes" DROP CONSTRAINT "user_incomes_user_wallet_id_fkey";
ALTER TABLE "user_outcomes" DROP CONSTRAINT "user_outcomes_user_id_fkey";
ALTER TABLE "user_outcomes" DROP CONSTRAINT "user_outcomes_user_wallet_id_fkey";
ALTER TABLE "user_outcomes" DROP CONSTRAINT "user_outcomes_user_budget_id_fkey";


DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "users_auth0";
DROP TABLE IF EXISTS "roles";
DROP TABLE IF EXISTS "user_roles";
DROP TABLE IF EXISTS "wallet_sources";
DROP TABLE IF EXISTS "wallet_currencies";
DROP TABLE IF EXISTS "user_wallets";
DROP TABLE IF EXISTS "transaction_periods";
DROP TABLE IF EXISTS "user_budgets";
DROP TABLE IF EXISTS "user_goals";
DROP TABLE IF EXISTS "goal_transactions";
DROP TABLE IF EXISTS "user_transfers";
DROP TABLE IF EXISTS "user_incomes";
DROP TABLE IF EXISTS "user_outcomes";
